/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

/**
 *
 * @author alexa
 */
public class HomeAdminPage extends javax.swing.JFrame {

    /**
     * Creates new form HomeAdmin
     */
    public HomeAdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        regras = new javax.swing.JButton();
        jogar = new javax.swing.JButton();
        questoesBotao = new javax.swing.JButton();
        resultadoBotao = new javax.swing.JButton();
        texto1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeIcon.jpg"))); // NOI18N
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo3Python.jpg"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logOut.icon.jpg"))); // NOI18N
        logout.setBorder(null);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 600, -1, -1));

        regras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HomeBotaoRegras.jpg"))); // NOI18N
        regras.setBorder(null);
        regras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regrasActionPerformed(evt);
            }
        });
        getContentPane().add(regras, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, -1));

        jogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HomebotaoJogar.jpg"))); // NOI18N
        jogar.setBorder(null);
        jogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarActionPerformed(evt);
            }
        });
        getContentPane().add(jogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, -1, -1));

        questoesBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/QuestoesBotao.jpg"))); // NOI18N
        questoesBotao.setBorder(null);
        questoesBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questoesBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(questoesBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        resultadoBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ResultadosBotao.jpg"))); // NOI18N
        resultadoBotao.setBorder(null);
        resultadoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(resultadoBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 380, -1, -1));

        texto1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        texto1.setText("Olá administrador");
        getContentPane().add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        texto2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        texto2.setText("Você é responsável por criar, consultar, alterar e excluir os exercícios que");
        getContentPane().add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        texto3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        texto3.setText("serão apresentados para os alunos durante o jogo , além de consultar o");
        getContentPane().add(texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        texto4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        texto4.setText("resultado de cada aluno após o término da atividade.");
        getContentPane().add(texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/InicioPage.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        LoginPage1 frame = new LoginPage1();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutActionPerformed

    private void questoesBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questoesBotaoActionPerformed
        // TODO add your handling code here:
        QuestoesPage frame = new QuestoesPage();
        frame.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_questoesBotaoActionPerformed

    private void jogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarActionPerformed
        // TODO add your handling code here:
        ComecarAdminPage frame = new ComecarAdminPage();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jogarActionPerformed

    private void resultadoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoBotaoActionPerformed
        // TODO add your handling code here:
        ResultadosAdminPage frame = new ResultadosAdminPage();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_resultadoBotaoActionPerformed

    private void regrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regrasActionPerformed
        // TODO add your handling code here:
        RegrasPageAdmin frame = new RegrasPageAdmin();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel home;
    private javax.swing.JButton jogar;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logout;
    private javax.swing.JButton questoesBotao;
    private javax.swing.JButton regras;
    private javax.swing.JButton resultadoBotao;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    // End of variables declaration//GEN-END:variables
}
