/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;
import java.util.Random;
import javax.swing.JFrame;
import jutil.Jogador;
/**
 *
 * @author alexa
 */
public class JogoPage extends javax.swing.JFrame {
    
    jutil.Jogador jogador;
    /**
     * Creates new form JogoPage
     */
    public JogoPage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public void setJogador(jutil.Jogador jogador){
        this.jogador = jogador;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roletaBotao = new javax.swing.JButton();
        logOutBotao = new javax.swing.JButton();
        questao = new javax.swing.JLabel();
        JogoFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roletaBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/roletaBotao-removebg-preview.png"))); // NOI18N
        roletaBotao.setBorder(null);
        roletaBotao.setBorderPainted(false);
        roletaBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roletaBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(roletaBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        logOutBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logOut.icon.jpg"))); // NOI18N
        logOutBotao.setBorder(null);
        logOutBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(logOutBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 620, -1, 40));

        questao.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        questao.setForeground(new java.awt.Color(153, 204, 255));
        questao.setText("1");
        getContentPane().add(questao, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 50, 30));

        JogoFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/JogoPage.png"))); // NOI18N
        getContentPane().add(JogoFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roletaBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roletaBotaoActionPerformed
        // TODO add your handling code here:
        
        int categoria;
        Random random = new Random();
        
        categoria = random.nextInt(4);
        
        switch (categoria){
             
            case 0 -> {
                Categoria1Page page1 = new Categoria1Page(this, jogador);
                page1.setVisible(true);
                this.setVisible(false);
                break;
            }
            case 1 -> {
                Categoria2Page page2 = new Categoria2Page(this, jogador);
                page2.setVisible(true);
                this.setVisible(false);
                break;
            }
            case 2 -> {
                Categoria3Page page3 = new Categoria3Page(this, jogador);
                page3.setVisible(true);
                this.setVisible(false);
                break;
            }
            case 3 -> {
                Categoria4Page page4 = new Categoria4Page(this, jogador);
                page4.setVisible(true);
                this.setVisible(false);
                break;
            } 
          
        }
    }//GEN-LAST:event_roletaBotaoActionPerformed

    private void logOutBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBotaoActionPerformed
        // TODO add your handling code here:
        LoginPage1 frame = new LoginPage1();
        frame.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_logOutBotaoActionPerformed
    
    public void AlteraTextoRodada( int i){
        questao.setText(Integer.toString(i));
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JogoFundo;
    private javax.swing.JButton logOutBotao;
    private javax.swing.JLabel questao;
    private javax.swing.JButton roletaBotao;
    // End of variables declaration//GEN-END:variables
}
