/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jutil.conector;
import jutil.Jogador;

/**
 *
 * @author alexa
 */
public class LoginPage1 extends javax.swing.JFrame {

    
    Jogador jogador = new Jogador();
    
    /**
     * Creates new form LoginPage1
     */
    public LoginPage1() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        senhaInserir.setEchoChar('\u25cf');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        nomes = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        pontosIcone = new javax.swing.JLabel();
        LogoMaua = new javax.swing.JLabel();
        imt = new javax.swing.JLabel();
        dif = new javax.swing.JLabel();
        des = new javax.swing.JLabel();
        entrarBotao = new javax.swing.JButton();
        cadastrarBotao = new javax.swing.JButton();
        senhaInserir = new javax.swing.JPasswordField();
        usuarioInserir = new javax.swing.JTextField();
        login = new javax.swing.JLabel();
        usuarioTexto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fecharBotao = new javax.swing.JButton();
        tracos = new javax.swing.JLabel();
        verSenha = new javax.swing.JToggleButton();
        textoComentario = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoPython.jpg"))); // NOI18N
        Logo.setToolTipText("");
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        nomes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nomes.jpg"))); // NOI18N
        getContentPane().add(nomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, -1, -1));

        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PythonStepsTitulo.jpg"))); // NOI18N
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));
        getContentPane().add(pontosIcone, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, -1, -1));

        LogoMaua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoMaua.jpg"))); // NOI18N
        getContentPane().add(LogoMaua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IMT.jpg"))); // NOI18N
        getContentPane().add(imt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        dif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DifIcone.jpg"))); // NOI18N
        getContentPane().add(dif, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, -1, -1));

        des.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DesIcone.jpg"))); // NOI18N
        getContentPane().add(des, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, -1, -1));

        entrarBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginBotaoEntrar.jpg"))); // NOI18N
        entrarBotao.setBorder(null);
        entrarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(entrarBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 460, 150, 40));

        cadastrarBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginBotaoCadastrar.jpg"))); // NOI18N
        cadastrarBotao.setBorder(null);
        cadastrarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 460, -1, 40));

        senhaInserir.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(senhaInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 380, 170, 30));

        usuarioInserir.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(usuarioInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 300, 170, 30));

        login.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        login.setForeground(new java.awt.Color(255, 204, 0));
        login.setText("LOGIN");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 200, -1, -1));

        usuarioTexto.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        usuarioTexto.setForeground(new java.awt.Color(255, 204, 0));
        usuarioTexto.setText("Registro do Usuário:");
        getContentPane().add(usuarioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Senha:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 350, -1, -1));

        fecharBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginFecharBotao.jpg"))); // NOI18N
        fecharBotao.setBorder(null);
        fecharBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(fecharBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 560, 150, 40));

        tracos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TracosIcone.jpg"))); // NOI18N
        getContentPane().add(tracos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 250, -1, -1));

        verSenha.setBackground(new java.awt.Color(0, 102, 204));
        verSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verSenha.png"))); // NOI18N
        verSenha.setBorder(null);
        verSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(verSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 380, -1, 30));

        textoComentario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoComentario.setForeground(new java.awt.Color(255, 255, 255));
        textoComentario.setText("RA completo (com ponto e traço)");
        getContentPane().add(textoComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 330, -1, -1));

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginPage.png"))); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBotaoActionPerformed
        // TODO add your handling code here:
        CadastroPage Cadastro = new CadastroPage();
        Cadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastrarBotaoActionPerformed

    private void fecharBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharBotaoActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_fecharBotaoActionPerformed

    private void entrarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBotaoActionPerformed
        // TODO add your handling code here:
        
        
        try (Connection con = conector.getConnection();) {
            Statement stmt = con.createStatement();

            String SQLUser = "SELECT * FROM `pythonsteps`.`usuarios` WHERE ra='" + usuarioInserir.getText() + "'";
            ResultSet rs = stmt.executeQuery(SQLUser);

            if (rs.next()) {
                if (rs.getNString("senha") == null ? senhaInserir.getText() == null : rs.getNString("senha").equals(senhaInserir.getText())) {
                    if (rs.getNString("admin").equals("0")) {
                        JOptionPane.showMessageDialog(null, "Conectando!");
                        jogador.SalvarNome(rs.getNString("nome"));;
                        jogador.SalvarRA(rs.getNString("ra"));
                        jogador.SalvarID(rs.getInt("idUsuario"));
                        jogador.SalvarIsAdmin(rs.getInt("admin"));
                        
                        
                        HomePage frame = new HomePage();
                        frame.setVisible(true);
                        frame.setJogador(jogador);
                        this.dispose();

                        con.close();
                        stmt.close();
                        rs.close();
                    } else if (rs.getNString("admin").equals("1")) {
                        JOptionPane.showMessageDialog(null, "Conectando Admin!");
                        jogador.SalvarNome(rs.getNString("nome"));;
                        jogador.SalvarRA(rs.getNString("ra"));
                        jogador.SalvarID(rs.getInt("idUsuario"));
                        jogador.SalvarIsAdmin(rs.getInt("admin"));
                        
                        HomeAdminPage frame = new HomeAdminPage();
                        frame.setVisible(true);
                        frame.setJogador(jogador);
                        this.dispose();

                        con.close();
                        stmt.close();
                        rs.close();
                    } else {
                        JOptionPane.showMessageDialog(null, "Impossível verificar sua permissão! Contatar um administrador!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "A senha informada está incorreta!");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Usuário inexistente!");
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_entrarBotaoActionPerformed

    private void verSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verSenhaActionPerformed
        // TODO add your handling code here:
        if (verSenha.isSelected()){
            senhaInserir.setEchoChar((char)0);
        }else{
            senhaInserir.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_verSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel LogoMaua;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton cadastrarBotao;
    private javax.swing.JLabel des;
    private javax.swing.JLabel dif;
    private javax.swing.JButton entrarBotao;
    private javax.swing.JButton fecharBotao;
    private javax.swing.JLabel imt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel login;
    private javax.swing.JLabel nomes;
    private javax.swing.JLabel pontosIcone;
    private javax.swing.JPasswordField senhaInserir;
    private javax.swing.JLabel textoComentario;
    private javax.swing.JLabel tracos;
    private javax.swing.JTextField usuarioInserir;
    private javax.swing.JLabel usuarioTexto;
    private javax.swing.JToggleButton verSenha;
    // End of variables declaration//GEN-END:variables
}
