/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

/**
 *
 * @author alexa
 */
public class RegrasPage extends javax.swing.JFrame {

    /**
     * Creates new form regrasPage
     */
    public RegrasPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setaVoltar = new javax.swing.JButton();
        regrasFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 682));
        setMinimumSize(new java.awt.Dimension(1366, 682));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 562));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setaVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/setaVoltar.jpg"))); // NOI18N
        setaVoltar.setBorder(null);
        setaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setaVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(setaVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 60, 50));

        regrasFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/RegrasPage.png"))); // NOI18N
        getContentPane().add(regrasFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setaVoltarActionPerformed
        // TODO add your handling code here:
        
        HomePage frame = new HomePage();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_setaVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegrasPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegrasPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegrasPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegrasPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegrasPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel regrasFundo;
    private javax.swing.JButton setaVoltar;
    // End of variables declaration//GEN-END:variables
}
